#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#ifdef __unix__
#define clear() system("clear")
#else
#define clear() system("CLS")
#endif
int main(){
    clear();
    srand(time(0));
    int guess, tries=5;
    int random_number = rand() % 50 + 1;

    printf("\n\xAF This is a simple guessing game in C. The program generates a random number bet 1 and 50.\n");
    printf("\xAF You have to guess the random number generated by the program, You have only 5 tries.\n");

    home:
    printf("\n\t \xAF Guess the number between 1 and 50 : ");
    scanf("%d", &guess);

    do {
        tries--;
        if(guess != random_number)
        {
            if(guess > random_number)
            {
                printf("\n\t\t \x1A Wrong guess, The number is lower than %d", guess);
            }
            else
            {
                printf("\n\t\t \x1A Wrong guess, The number is greater than %d.", guess);
            }
            printf("\n\t\t \x1A You have %d %s left.\n", tries, (tries==1) ? "try" : "tries");
            if(tries == 0 && guess != random_number)
            {
                printf("\n\n\t \x1A You lost, the correct answer was %d", random_number);
                exit(0);
            }
            goto home;
        }
        if (guess == random_number)
        {
            printf("\n\n\t \x1A Correct, the answer is %d", random_number);
            exit(0);
        }
    } while (tries > 0);
}